   - name: clone hastebin
     git:
       repo: https://github.com/seejohnrun/haste-server.git
       dest: /opt/hastebin
       force: yes

   - name: install node.js
     yum:
       name: nodejs
       state: latest
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: install node.js
      yum:
        name: nodejs
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

   - name: edit config
     template:
       src: config.js.j2
       dest: /opt/hastebin/config.js
       owner: root
       group: root
       mode: 644

   - name: Install hastebin
     npm:
       name: hastebin
       global: yes
       path: /opt/hastebin

   - name: Allow hastebin firewall
     command: firewall-cmd --zone=public --permanent --add-port=1337/tcp

   - name: Bounce firewalld
     service: name=firewalld state=restarted
